# Generated by Django 2.2.5 on 2021-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pub_date', models.DateField(verbose_name='发布时间')),
                ('author', models.CharField(default=None, max_length=64, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='开盘价')),
                ('close', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='收盘价')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='最低价')),
                ('updownd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='涨跌幅度')),
                ('turnrate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='换手率')),
                ('count', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
            ],
        ),
    ]
